### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by Lusitaniae** [GameXG/gitlab-runner-docker-cleanup#1]
I think it wold be better have more conservative defaults

for instance, 
```
DEFAULT_TTL=60m
CHECK_INTERVAL=30m
```
with current defaults its causing a couple of CI runs to fail from time to time.

**Comment by GameXG** [comment]
This repository is a copy of https://gitlab.com/gitlab-org/gitlab-runner-docker-cleanup.
For related issues, please go to https://gitlab.com/gitlab-org/gitlab-runner-docker-cleanup to submit.

**Comment by Lusitaniae** [comment]
Thank you

Can you also mention this in the project url/description or readme?

**Comment by Lusitaniae** [comment]
Actually these tools (Spotify also have similar one) are being deprecated and abandoned.

This one's last update was over 4 years ago.

Docker already have command to clean up stuff and better point users to it.

https://docs.docker.com/engine/reference/commandline/system_prune/
